### ISSUE TITLE
Label explicitly say EOS even thought is on a different chain.

### ISSUE THREAD

**Issue by Jzarecta** [greymass/anchor#1023]
This is a 'label bug' as the label explicitly talks about EOS even thought Anchor can be on different blockchains. It should be a dynamic variable that explains it in whatever chain the wallet is (TELOS, WAX, FIO, etc).
https://i.imgur.com/TlVWzwj.png

The dialog can be trigger from the Resources -> RAM -> Purchase button

**Comment by aaroncox** [comment]
This should be resolved as of 1.1.9. 

![image](https://user-images.githubusercontent.com/677686/104429468-a42d2280-5553-11eb-8ebf-8e2a811f5b97.png)

If it is not, please let me know which chain!
