### ISSUE TITLE
Possible to auto-sign transaction?

### ISSUE THREAD

**Issue by not-idol** [greymass/anchor#1035]
for every trx i need to manually click and sign it, is it possible to let it auto-sign?

**Comment by aaroncox** [comment]
It is not possible at this time. 

It is something we have been looking into over the past few months but have not released this feature yet.

**Comment by not-idol** [comment]
any idea on how to implement it by themself ?

**Comment by not-idol** [comment]
other question: is it possible to change the signing time ? i think for a trx its 1 or 2min time to sign

**Comment by aaroncox** [comment]
Scatter has whitelisting, which can sign transactions automatically if you set it up. I'm not familiar enough to explain it, but I know it exists. 

If you want to perform transactions automatically though, you'd be better off writing a small program that does it for you. There's a lot of these in the wild and are typically like 30-40 lines of javascript that loops to repeat a transaction at a set interval. 

As for expiration, the app developer creating the transaction can set the expiration time. You could go an hour pretty easily if you wanted. If it's a web application sending a transaction to Anchor, it's the web developer who gets to pick that expiration.

**Comment by not-idol** [comment]
ah okay thanks for the answers!

**Comment by mrDarky** [comment]
will Anchor have a whitelist like Scatter for auto sign in the near future?
