### ISSUE TITLE
Anchor Wallet not allowing Ledger Nano set-up

### ISSUE THREAD

**Issue by emmaivybriar** [greymass/anchor#1037]
I am trying to connect Ledger Nano S to my Anchor, but it keeps saying "Reinitializing....Establishing connection. Please Wait". Every time I open the EOS app on the Nano, it bounces me out of it. Anybody have a fix for this?

**Comment by aaroncox** [comment]
The connection to the Ledger can be blocked if other apps are accessing it. Some potential solutions can be found here:

https://forums.greymass.com/t/error-cannot-write-hid-device-using-anchor-wallet-ledger/326/2
