### ISSUE TITLE
Failing to build on macOS Big Sur (notarization issue)

### ISSUE THREAD

**Issue by amirbaer** [greymass/anchor#1051]
I am trying to build on macOS Big Sur (11.2.3), following the "Build it yourself" instructions on the main page.
The last command (`npm run package-mac`) fails.

electron-builder version: 22.6.0
electron version: v8.2.1

From what I understand:
- this command actually runs `npm run build && electron-builder --publish never -c internals/electron-builder.json`
- the `npm run build` part works file, the second part is where it fails

This seems to be the relevant part of the process:
![image](https://user-images.githubusercontent.com/4663287/111598847-4e395d00-87d8-11eb-8f88-eb11f5f00fd4.png)

Full logs:
[log.txt](https://github.com/greymass/anchor/files/6162626/log.txt)
[log-debug.txt](https://github.com/greymass/anchor/files/6162658/log-debug.txt)

Previously I also had this error:
![image](https://user-images.githubusercontent.com/4663287/111599629-2ac2e200-87d9-11eb-8697-22e8516bbf12.png)

I got rid of it by adding "./" before "internal/macos/notarize.js" in internals/electron-builder.json

Any help would be appreciated  🙏🏼

**Comment by aaroncox** [comment]
We should actually make that disabled by default. 

It's failing because you don't have the authority to notarize a build, and commenting that portion of the code out is the proper solution for the time being. Apple's notarization service is what lets us authorize macOS builds from us as a known developer.

**Comment by amirbaer** [comment]
Thanks for the quick response!

Indeed I was wondering if notarization is a crucial step considering I just want a local build.

Could you please instruct me how to comment out this step in the code?

**Comment by aaroncox** [comment]
I comment it out if I'm doing non-release builds as well, and this chunk of code is typically what I'll just comment out:

https://github.com/greymass/anchor/blob/1a8afbe49d8bb55aa47d7f36387ded52bfe99641/internals/macos/notarize.js#L12-L17

This `notarize` call is the one that communicates out to Apple and asks for the build to be notarized. Removing it prevents it and speeds up the build process dramatically.

**Comment by amirbaer** [comment]
Thank you Aaron, you're very kind 🙏 
I commented it out and it worked like a charm :)

I tested again for the "Cannot find model" error by removing the "./" and for some reason now the build process went through without a problem. Not sure about an explanation...

**Comment by amirbaer** [comment]
BTW, if this trick is a necessary step perhaps consider adding it to the instructions on the main page.
