### ISSUE TITLE
I am going to translate this app for chinese, any hints?

### ISSUE THREAD

**Issue by apporc** [greymass/anchor#1053]
I am translating this app to Chinese. I know those locale files are located at `app/renderer/assets/zh-CN/`.
If there are nothing special that i need to know in advance, soon i will create a pull request.

**Comment by apporc** [comment]
This is a pull request try:
https://github.com/greymass/anchor/pull/1054

Don't merge this one, i will add all translations together in one pull request later.

**Comment by aaroncox** [comment]
We are currently setup to use Crowdin for translations, I would recommend if you are starting, to start there: 

https://crowdin.com/project/eos-voter

However, one thing to note is there are many strings with are no longer used in the app - and we are planning on removing a lot more in the future. So if you do begin translating, some of that effort may go to waste in the future. This is why we have held off on doing translations, until a point in time where we clean up what will and will not be used. 

If you'd like to translate anyways with that knowledge, use the features of crowdin and it will become a part of our build process automatically, no need to do pull requests of your own.

**Comment by apporc** [comment]
Ok, i will wait till the refactor is over. Thank you.
