### ISSUE TITLE
Will GreyMass expose my Karma tokens for conversion?

### ISSUE THREAD

**Issue by ScotterMonk** [greymass/anchor#1061]
I want to convert my Karma (an EOS-based coin) to either EOS or an ERC-20 token, or really anything, heh.
Will GreyMass help with this? Scatter says it can but then bugs out at last step.
Thanks!

**Comment by aaroncox** [comment]
If you can find an exchange or swapping service that supports Anchor, it might. 

I'm not knowledgable about Karma or where it's traded though so I can't be of much help there.
