### ISSUE TITLE
[Tools/Smart Contracts] Action parameters not serialized

### ISSUE THREAD

**Issue by smlu** [greymass/anchor#1066]
When creating transaction (Tools/Smart Contracts) with below example transaction as parameter of a contract action, Anchor sends such transaction without serialized data field for every action.
Example of such contract would be `eosio.msig` where you end up with invalid transaction being proposed.

Note: [bloks.io](https://bloks.io) blocks such transaction parameter if action data is not serialized. 
         I guess it's better than sending invalid transaction to the chain but I think it would be even better if
         Anchor could serialize action data on it's own as documented on [developers.eos.io](https://developers.eos.io/manuals/eosjs/latest/how-to-guides/how-to-propose-a-multisig-transaction/#serializing-actions)
```
{
    "expiration": "2021-03-27T18:07:23.000",
    "ref_block_num": 0,"ref_block_prefix": 0,
    "max_net_usage_words": 0, "delay_sec": 0,
    "max_cpu_usage_ms": 0,
    "context_free_actions": [],
    "actions": [
        { 
            "account": "testcontract",
            "name": "testaction",
            "data": { "paramname": "paramval" },
             "authorization": [
                { 
                    "actor": "testaccount", 
                    "permission": "active" 
                }
            ] 
        } 
    ],
    "transaction_extensions": []
}
```

**Comment by aaroncox** [comment]
I think this should be relatively easy to change. 

The reason they aren't serialized is actually for readability purposes, both in the tool and when using a watch/cold wallet combo. I think we can change it to use serialized actions specifically within the Tools/Smart Contracts area while leaving the cold/watch wallet combo alone. 

The reason I think it's useful for watch/cold wallets is that the user transports the transaction manually in a JSON file. If they are an advanced enough user, they'd be able to open the JSON file and inspect that data to ensure they are signing the transaction they anticipated, even without needing to trust Anchor displaying it properly.

**Comment by aaroncox** [comment]
I just did some testing against this, and the tests I did were resulting in serialized action data. 

What kind of setup were you using that encountered the unserialized actions? Was it a watch wallet, what contract/action was it, etc etc. Any additional information you can provide that allows me to reproduce would be useful 👍

**Comment by smlu** [comment]
Yeah sure. I'm using 'regular' Anchor wallet version 1.1.12. We're building WebAuthn based multisig contract called `row`. The `row` smart contract is uploaded on jungle 3 testnet under the account name [irowyourboat](https://jungle3.bloks.io/account/irowyourboat). The contract mimics scheme from `eosio.msig` contract (`propose`, `approve`, `exec` etc...). The `propose`  is the action in question. 

For testing I've made 2 transactions [63f301bc](https://jungle3.bloks.io/transaction/63f301bc07024ea3434d512d5e98f29088b0f97002101e37219c3fd615764c62) and [a5ca72da](https://jungle3.bloks.io/transaction/a5ca72dab98a91d012f9497be4239f57a9d5345c433e66efea54d20208fc32e8) both were published with Anchor wallet. 

The [ 63f301bc](https://jungle3.bloks.io/transaction/63f301bc07024ea3434d512d5e98f29088b0f97002101e37219c3fd615764c62) proposed this transaction using unserialized parameters:
```
{
    "expiration": "2021-04-27T18:07:23.000",
    "ref_block_num": 0,"ref_block_prefix": 0,
    "max_net_usage_words": 0, "delay_sec": 0,
    "max_cpu_usage_ms": 0,
    "context_free_actions": [],
    "actions": [
        { 
            "account": "irowyourboat",
            "name": "hi",
            "data": { "nm": "rowuseruser1" },
             "authorization": [
                { 
                    "actor": "rowuseruser1", 
                    "permission": "active" 
                }
            ] 
        } 
    ],
    "transaction_extensions": []
}
```

The [a5ca72da](https://jungle3.bloks.io/transaction/a5ca72dab98a91d012f9497be4239f57a9d5345c433e66efea54d20208fc32e8) proposed this transaction using serialized parameters:
```
{
    "expiration": "2021-04-27T18:07:23.000",
    "ref_block_num": 0,"ref_block_prefix": 0,
    "max_net_usage_words": 0, "delay_sec": 0,
    "max_cpu_usage_ms": 0,
    "context_free_actions": [],
    "actions": [
        { 
            "account": "irowyourboat",
            "name": "hi",
            "data": "10aec2fa2aac39bd",
             "authorization": [
                { 
                    "actor": "rowuseruser1", 
                    "permission": "active" 
                }
            ] 
        } 
    ],
    "transaction_extensions": []
}
```

As you can see the proposed transaction in [ 63f301bc](https://jungle3.bloks.io/transaction/63f301bc07024ea3434d512d5e98f29088b0f97002101e37219c3fd615764c62) has `null` data field.

If it's any of help the source code for row contract is [here](https://github.com/ZeroPass/row.contract).
If you need any more information please let me know!

**Comment by aaroncox** [comment]
I think I have a fix in the next version for this. It's detecting if the data type of a field is `transaction`, and if so, it's load the appropriate ABI and serialize the action data within it automatically.

I'll include this in 1.2.2 and hopefully it'll work for your use case.

**Comment by smlu** [comment]
Awesome, thanks for this patch!
