### ISSUE TITLE
Clicking on wax balance rounds UP on Transfer Tokens screen

### ISSUE THREAD

**Issue by tvl83** [greymass/anchor#1077]
![image](https://user-images.githubusercontent.com/141966/114092980-2772c180-9880-11eb-8d1e-b35e2cca298b.png)

My balance is 3258 and change. When I click on the balance number it rounds it up to 3259 which resulted in a `precision_mismatch` error. I didn't realize it rounded and I added 4 zeroes to the end after the decimal (I thought the precision was 4 for WAX, but it actually made it a total of 8 zeroes and with the proper precision it threw an `balance_overdraw` error.

**Comment by aaroncox** [comment]
This appears to happen with all token balances, we'll investigate and get this resolved. Thanks for the heads up! 👍
