### ISSUE TITLE
Update doesn't seem to open & won't connect to UX

### ISSUE THREAD

**Issue by Another-Joe** [greymass/anchor#1081]
I had 1.1.12 AppImage installed, which seems to be working fine. But when I tried to connect to https://utilityx.io/swap it won't connect. I've tried on Firefox and Chrome. Firefox did nothing at all. Chrome provided a popup to confirm that I wanted to open Anchor, but did nothing after I confirmed.

I downloaded 1.2 AppImage, but when I open it the wallet still says that it's 1.1.12. I tried to see if anything behaved differently on https://utilityx.io/swap, but it's the same.

What to do?

**Comment by aaroncox** [comment]
It's possible the install worked, but the older version was still running in the background which is what you're seeing. There is a bug in the Windows/Linux versions where the "Close" and "Exit" buttons were reversed, making closing the app pretty confusing.

I'd say the first thing to try is looking in the system tray (near the clock) to see if Anchor is running there. If it is shown in the system tray, right click the icon and exit from there to make sure the app closes. 

Then try starting the app back up and see if it is the newest version. 

Second thing I'd try is using the in-app update. It's available from the home screen or from the "Help" menu under "Check for Updates". This will perform an update in place and then prompt to restart the app - which should do the trick.

**Comment by Another-Joe** [comment]
Thanks Aaron. 

Yeah, that helped. I did the internal update and shut it off and back on and it's updated.

Unfortunately, it still won't sign in to UX. I tried both Firefox and Chrome again. They don't seem to want to talk to Anchor at the moment.

**Comment by aaroncox** [comment]
Ah - yeah sorry I didn't address that earlier. 

https://github.com/greymass/anchor/issues/833

The AppImage currently is generating the desktop file incorrectly. The above github issue shows the problem as well as a workaround you can do to get that working. With that desktop file edited to add the `%U` and Anchor restarted, it should trigger those links.

One final thing to check is the "App Integration" section on the home screen - make sure it's enabled.

**Comment by Another-Joe** [comment]
Thanks Aaron,

I started looking for that file, but I don't know my way around well enough. Sounds like I'm better off just taking the .deb route? 

Kind regards.

(I don't get to GitHub often. Should I "Close with comment"?)

**Comment by Another-Joe** [comment]
Well, it's not working for me either. I just can't get it installed from .deb and am stumped. Maybe I'm missing a step.

I've installed it and ran sudo dpkg -i ./linux-anchor-wallet-1.2.1-amd64.deb in Terminal. It seemed to work, but I can't open Anchor at all now.

Sorry for the hassle. Maybe I'm missing a step?

Thanks

**Comment by aaroncox** [comment]
Is Anchor still running in the system tray by chance? There may be an icon sitting near the clock and other icons and the old version may still be running, which isn't letting the new one run. 

The steps you're performing look right in terms of installing it.

**Comment by Another-Joe** [comment]
I'm stumped. 

When I ran dpkg, it said that it was overwriting the same version. But I had deleted the AppImage, so I'm not sure what's going on there.
In order to make sure nothing was happening in the background, I restarted. The Anchor icon is still on my App page, but it won't open.

Any ideas?

**Comment by Another-Joe** [comment]
Tried again. It's working. Thanks!

**Comment by aaroncox** [comment]
Awesome glad to hear it, and sorry for the delay in responding!
