### ISSUE TITLE
Desktop app does not find wax wallet

### ISSUE THREAD

**Issue by jswainst** [greymass/anchor#1083]
I have created two wax accounts, one via the Anchor iOS app and one via the wax cloud wallet using a private key generated in the desktop app. I imported both private keys into the Anchor desktop app. When searching for accounts it detects nothing. I can see both accounts on the bloks.io site.

**Comment by jswainst** [comment]
It looks like it just took a few hours for it to recognize it or something but it found one of them at least.

**Comment by aaroncox** [comment]
Ah sorry about that. Yeah, current we're working through some troubles with one of the lookup services for WAX and it fell behind today. That was the source of it not showing up for a while. 

We're hoping to have those hiccups resolved soon.
