### ISSUE TITLE
"open anchor app" button is not working

### ISSUE THREAD

**Issue by mostar** [greymass/anchor#1101]
Hi

Following issue https://github.com/greymass/anchor/issues/949
In my case there is no 
appimagekit...anchor....desktop
file in ~/.local/share/applications directory and "open anchor app" button is not work
I'm using
linux-anchor-wallet-1.2.2-x86_64.AppImage

Is there any other way to connect site like https://arm.chintai.io/portal to anchor ?

**Comment by aaroncox** [comment]
If possible, the deb installer (instead of the AppImage) will setup everything properly. I'm not sure which linux distribution you're using but the AppImage itself is the only one with this problem currently.

**Comment by aaroncox** [comment]
Also for reference: https://github.com/greymass/anchor/issues/833

We are tracking this in the above issue.
