### ISSUE TITLE
ANCHOR - unable to connect to the WAX blockchain

### ISSUE THREAD

**Issue by zoobie702** [greymass/anchor#1106]
I'm having issues trying to log into a blockchain and I'm instructed to try and find a API node; however, I get the attached instructions and I'm still unable to get this to work properly.  Please help get this addressed today.  I have a lo of assets locked up that I'm unable to get a hold of. 

[unable to connect to the WAX blockchain.docx](https://github.com/greymass/anchor/files/6453091/unable.to.connect.to.the.WAX.blockchain.docx)

**Comment by zoobie702** [comment]
i had tried to login to my anchor wallet again (happyzoobie2), and i'm getting the following error message when i try to connect to an API... Could you please help me out with this one?  i have a lot of NFT's just sitting in there along with a lot of crypto.  Your help in greatly appreciated.  i took some screenshots of the issue.

![image](https://user-images.githubusercontent.com/82052307/118300695-d7eb6b00-b4a7-11eb-8bd6-d529a72614de.png)

![image](https://user-images.githubusercontent.com/82052307/118300484-9b1f7400-b4a7-11eb-8015-c9a6abd2bbc8.png)

![image](https://user-images.githubusercontent.com/82052307/118300711-dcb01f00-b4a7-11eb-9fe3-47678f9ea081.png)

**Comment by aaroncox** [comment]
It looks like the eosusa.news API endpoint is not working properly.

I'd recommend going into Manage Blockchains and changing the API node. For WAX, you're free to use ours:

https://wax.greymass.com

**Comment by zoobie702** [comment]
Hi Aaron,

Could you please kindly share how to change the API node?  When I enter and
paste the link you had given me in the "Default node for this blockchain"
the save button is not working.  Thank you so much for your assistance in
advance.  It's imperative  i get this working again since I have a lot of
nft's and crypto locked in this account.

[image: image.png]

**Comment by aaroncox** [comment]
If you go into the blockchains dropdown, click “Manage Blockchains”, and then hit the little gear next to it, you’ll be able to change the API node.

**Comment by MFCB7** [comment]
I'm with the same problem, in the atomic wax my wallet open this:

![problema carteira anchor](https://user-images.githubusercontent.com/84642166/119239311-a5ccaf80-bb1e-11eb-8da1-06ab2ab7d331.PNG)

Before was showing the same thing but with wax blockchain.

Someone can help me?

**Comment by aaroncox** [comment]
It looks like it's trying to login with an EOS account. There are two versions of AtomicHub, one of EOS and one for WAX. Make sure you're on the right one if you're trying to login to the right one:

EOS: https://eos.atomichub.io/
WAX: https://wax.atomichub.io/

**Comment by zoobie702** [comment]
Aaron,

Sorry, but I have copied and pasted the API node (from this link
https://wax.greymass.com) in the dfuse API Key, and I still cannot get
access to my wallet. Anything you can do to assist me would be greatly
appreciated.  Anyway we can do a Teams meeting and I can grant you remote
access to my desktop.  It's important I can get to a few of my NFT's that
are stored in this wallet soon.



[image: image.png]

**Comment by aaroncox** [comment]
The "dfuse API Key" isn't where you change the API server address, that's done through the Manage Blockchains setting. 

There's a description of how to change the API server/node address in this forum thread:

https://forums.eoscommunity.org/t/issue-with-connecting-to-wax-blockchain/3305/10?u=aaron
