### ISSUE TITLE
Mobile Anchor is without any 

### ISSUE THREAD

**Issue by Jotka108** [greymass/anchor#1111]
I installed the Mobile Anchor App and imported 3 accounts via QR code. But than i recognized that there is nothing like a password or biometric step to secure the wallet. just click the Anchor button and you are in. Everybody who has my Smartphone can use it or send the private key. I didn´´t found a possibility to insert a password, which should be in the beginning after the app is installed.

**Comment by aaroncox** [comment]
Which version did you install? iOS, Android?

**Comment by Jotka108** [comment]
Android 0.16

**Comment by Jotka108** [comment]
Thanks, i received now the answer, it was I thought. It is your App but password is not possible at the moment. Would be nice if you can still change this, or at least so that the private key is protected before watching/sending with a password and/or G2FA.

**Comment by aaroncox** [comment]
Yeah agreed, that would be nice to have. We're still in early access so much will still change, thanks for the feedback and glad you got the answer on the forums.

I'm going to close this out since this is the github issues for the desktop version.
