### ISSUE TITLE
Nearly every action gives me an error message

### ISSUE THREAD

**Issue by lemireray** [greymass/anchor#1114]
I can't change my proxy vote, can't unstake any of my funds.  I've been unable to access more gas.  Transferring to token pocket with my private key failed.  This is getting very frustrating.

**Comment by lemireray** [comment]
Also, doing an update to the wallet never shuts down.

**Comment by lemireray** [comment]
The wallet is a Greymass wallet from 2017(?).  Last unstaked and extracted 500 EOS without a problem about 6 weeks ago and the remaining 500 EOS now seem frozen

**Comment by aaroncox** [comment]
So you're using a really early version of eos-voter? I think you'll probably need to upgrade before it'll work if its from really early on.

This was the last release of eos-voter, which I still think works:

https://github.com/greymass/eos-voter/releases/tag/v0.7.12

The automatic update doesn't work with versions that old unfortunately. If you take and install the version above, you should at least be able to use the network. If you'd like to upgrade to Anchor (the new version of the wallet), there's a guide on that here:

https://greymass.com/en/blog/migrating-to-anchor-from-eos-voter-greymass-wallet/

You're also welcome to ask questions in the Anchor forum should you have any:

https://forums.eoscommunity.org/c/greymass/anchor-wallet/5

Hope that helps!

**Comment by lemireray** [comment]
Thank you Aaron.  That's been excellent except for 1 problem.  I downloaded the Anchor wallet ... all good.  Then went to the EOS voter - Manage tools and there was no Save Backup box.  Import Accounts box is there all by itself.  Now what?

**Comment by aaroncox** [comment]
That's why I shared the link to eos-voter 0.7.12 as the first link. You can use that to upgrade your copy of eos-voter so it does have the Save Backup option. 

Both eos-voter and Anchor can be installed at the same time too, which allows you to go through this migration process.

**Comment by lemireray** [comment]
Thank you Aaron.  You are a champion.  I followed your advise and finally succeeded.  I now again have access to my funds.  I'm not well versed on the how and why of certain actions but I did unstake 50 of my 250 EOS from CPU and it registered as 191 still staked.  I'm guessing that is normal.  I did change my proxy vote to Greymass and was very happy to do so.  The last thing I'll ask of you is to send me your address so that I can send you a tip.  Thank you again for helping me out of this dilemma.

**Comment by lemireray** [comment]
I don't have any BAT.  I was hoping for your EOS address.

**Comment by aaroncox** [comment]
A tip is definitely not required, but appreciated if you feel its warranted. We're on a mission to make all of this much easier than it has been in the past and even more so than it is today. 

We have a forum post up about donations/tips here: https://forums.eoscommunity.org/t/donating-to-the-efforts-of-greymass/825

Feel free to ask questions on the forums as well in the Anchor category if you need further assistance!
