### ISSUE TITLE
Invalid Private Key

### ISSUE THREAD

**Issue by SoLegendary1** [greymass/anchor#1117]
Hi,

I have limited knowledge so please bear with me.  I set up the anchor wallet using Bloks.io to use on Wax, I followed a tutorial (https://www.youtube.com/watch?v=UZUtlWn4LUs&t=67s) which showed generating two private and public keys, active and owner .  The wallet has worked fine allowing me to receive wax, purchase and transfer some NFT's.  However I've tried to send some Wax back to my wax wallet and I get the error message "invalid private key".  Any help would be appreciated.

![image](https://user-images.githubusercontent.com/84638566/119236040-28f50200-bb2d-11eb-9b90-b560e89b66e0.png)

**Comment by aaroncox** [comment]
Hrm, just watched that video to get a sense of what you went through, and just so I get it straight you:

- Logged in with your WAX Cloud Wallet into bloks.
- Generated some new key pairs.
- Created a brand new account using those keys pairs.
- Loaded that new account in Anchor.

Am I following the process alright at this point? 

If so - how did you do the import, did you have to use the manual import or did you "import via private key" and it automatically found your account?

**Comment by SoLegendary1** [comment]
Thanks for getting back to me.  Yes, you are correct up to that point.  After that it was a case of "import using private key" and that found my account.  Like the screenshot from the youtube video below.

![image](https://user-images.githubusercontent.com/84638566/119239853-d541e300-bb43-11eb-970b-d08b1aa52a51.png)

**Comment by SoLegendary1** [comment]
I tried the transaction about five times earlier today and got this each time, I've just tried it again now and its worked.  Thanks for your time.

**Comment by aaroncox** [comment]
Interesting, not sure what was happening then! We'll keep our eyes peeled for anything similar to this, and feel free to let us know if you run into it agian.

**Comment by lolentbuu** [comment]
i found a solution on this one, so i followed the same tutorial on youtube wherein it said that we must generate two private keys one for active and one for the owner. So now, im trying to get out my wax into anchor wallet but i keep getting invalid key. So what i did was, i import another wallet and the private key i used is the "owner" private key. I tried sending out my wax and it worked.
