### ISSUE TITLE
Wax signin option. 

### ISSUE THREAD

**Issue by saycubed** [greymass/anchor#1123]
I have a websignin running  but it only has options for wax cloud wallet, how can I add anchor to the signing? I am running the https://www.npmjs.com/package/@waxio/waxjs

**Comment by aaroncox** [comment]
You'll need to either use a package like UAL (https://github.com/EOSIO/universal-authenticator-library) or use our anchor-link package directly (https://github.com/greymass/anchor-link. There's a guide here for the latter:

https://forums.eoscommunity.org/t/integrating-an-app-with-anchor-using-anchor-link/165

Questions about Anchor integrations can be posted here:

https://forums.eoscommunity.org/c/eosio-development/anchor-link/7
