### ISSUE TITLE
(windows) Application window never appears

### ISSUE THREAD

**Issue by hypersoph** [greymass/anchor#1132]
The Anchor application never shows up for me except  for signing requests. Even when I close and re-open the application it's just...invisible.

**Comment by aaroncox** [comment]
There's a few possible reasons for this. 

The first one is that Anchor lives in the system tray near the clock on the menu bar. If you close the main window, it closes down to that position and you can click that icon to make it reappear. 

The second being related to the monitor setup of the computer. Any chance you use more than one monitor? Anchor tries to remember the last position and open in the same place - so if monitor configurations change, sometimes it ends up in a place that doesn't exist. Maybe we should remove this "feature" 😅

**Comment by hypersoph** [comment]
> 
> 
> There's a few possible reasons for this.
> 
> The first one is that Anchor lives in the system tray near the clock on the menu bar. If you close the main window, it closes down to that position and you can click that icon to make it reappear.
> 
> The second being related to the monitor setup of the computer. Any chance you use more than one monitor? Anchor tries to remember the last position and open in the same place - so if monitor configurations change, sometimes it ends up in a place that doesn't exist. Maybe we should remove this "feature" 😅

My monitor wasn't connected at the time but I do use multiple monitors. I connected it and it's not showing up still. I also use an application that kind of adds multiple screens like it's a tablet pc? I can see there's a window but it's nowhere to be seen

**Comment by aaroncox** [comment]
It could have either been that the monitor wasn't connected, or the multiple screen application. Clicking that system icon is going to put it right back where it thinks it should be.

We have a new release coming up pretty soon - I'll open an issue to remove that bit of code so the window just opens on whatever screen is the default. Sorry about the hassle!
