### ISSUE TITLE
lemireray

### ISSUE THREAD

**Issue by lemireray** [greymass/anchor#1136]
On my Greymass and anchor wallets,  I just rented cpu via Power up, but got nothing for my deducted amount.

**Comment by lemireray** [comment]
I took a wrong turn.  I'm OK now.  Problem solved.

**Comment by aaroncox** [comment]
Awesome, glad to hear it. If you've got questions, feel free to ask them over on the forums as well! 

https://forums.greymass.com/c/greymass/anchor-wallet/5
