### ISSUE TITLE
Duplicate sessions created for same address

### ISSUE THREAD

**Issue by tvl83** [greymass/anchor#1142]
`const identifier = 'fiomarketplace';`

My login code

```typescript
    async login(): Promise<any> {
        const identity  = await link.login(identifier);
        const {session} = identity;
        this.session    = session;
        await this.setLoggedIn(true);
    }
```
Logout code

```typescript
    async logout(): Promise<any> {
        await this.session.remove();
        this.selectedAccount = null;
        this.selectedAccount$.next(this.selectedAccount);
        this.isLoggedIn$.next(false);
    }
```

I am pretty sure I am using this correctly. THe functionality seems to work just fine as far as removing the session from the browser.

The problem I am having is in Anchor there are duplicate sessions being created if I log out then back in with the same user.

![image](https://user-images.githubusercontent.com/141966/124524049-1114cd00-ddbf-11eb-9891-dfd2a3e0373d.png)

This doesn't affect the functionality of the website, just creates stale sessions in anchor. 

I can link to a demo website in the next week or so. Nothing is ready for public view right now and the repo is private. If I need to give access to the repo to investigate the problem I will do that no problem. The current site is pointed at a private testnet.

**Comment by aaroncox** [comment]
I transferred this issue over to the Anchor desktop repository, since its an issue affecting Anchor itself and not anchor-link.

We have a fix in place for the next release that will prevent duplicates like this as well 👍

**Comment by tvl83** [comment]
sounds good! Thanks!
