### ISSUE TITLE
Websocket error message box

### ISSUE THREAD

**Issue by stone89son** [greymass/anchor#1151]
![tatata](https://user-images.githubusercontent.com/6795515/129474201-e005c017-7102-4329-823a-69ab4492630e.JPG)

**Comment by aaroncox** [comment]
The next version will resolve this issue, and we are in the process of testing it right now. Hopefully we'll have a new release this week that includes this fix 👍

**Comment by ebirbe** [comment]
I'm also having this bug kite frequently when there is some small internet interruption or after the laptop hybernates.

**Comment by aaroncox** [comment]
We just published a pre-release version we believe resolves these issues. I'd invite you to try it out and see if it resolves the issue for you:

https://github.com/greymass/anchor/releases/tag/v1.2.7
