### ISSUE TITLE
Purchase RAM in wallet error message

### ISSUE THREAD

**Issue by tedimsdale** [greymass/anchor#1153]
Hello, I set up Anchor wallet for WAX using following video. All fine.

https://www.youtube.com/watch?v=tGiFr_LEyKA&feature=youtu.be

Now getting the message
"Error
Invalid private key ()" when trying to purchase more RAM.

Please help!

![image](https://user-images.githubusercontent.com/41115900/129803575-be4b6af1-e261-4240-875e-b40ff851ed9d.png)

Kind regards,
Tom

**Comment by tedimsdale** [comment]
CORRECTION: it was this video https://www.youtube.com/watch?v=UZUtlWn4LUs and it had two separate keys for Owner and Active.

**Comment by aaroncox** [comment]
Ensure you have the latest version of Anchor and that your wallet is unlocked. If you need more support, I'd encourage you to start a discussion about it on the forums: https://forums.eoscommunity.org/c/greymass/anchor-wallet/5
