### ISSUE TITLE
Manage tracked token issue 

### ISSUE THREAD

**Issue by Renzono** [greymass/anchor#1157]
The tokens used in Vigor protocol are missing in traked token list and it is not possible to add all of  them manually.
FYI  I was able to add only one manually
the required token are PBTC, IQ, VIG, VIGOR, USDT

**Comment by aaroncox** [comment]
The Vigor team is free to add all of these tokens to the smart contract which powers Anchor's token list:

https://github.com/greymass/customtokens

We can add them as well to the contract, we would just need to know the token contract name, token symbol, and token precision for each one to be added. I'm not familiar with some of these tokens and not sure where to find the information myself.
