### ISSUE TITLE
No Transaction !!!!!

### ISSUE THREAD

**Issue by TripleX11** [greymass/anchor#1169]
I attempt sending EOS, I click submit and get a transaction copy and a screen saying successful but NO funds have been removed from my account and the txt number doesn't exist.... What is going on here ?

**Comment by aaroncox** [comment]
There's an issue we're trying to identify on the network itself that's stopping transactions somewhere as its being relayed from APIs to block producers. Anchor is successfully broadcasting the transaction, and the first server you send it to is accepting the transaction as valid and starting the relay process. It's getting lost after that.

Sadly its a silent failure and hard to track - but we (along with others) are investigating what's going on.

**Comment by aaroncox** [comment]
Also to note - it should be working again now, since restarting a few things seems to resolve the problem for a short period of time. We just restarted everything and are planning on trying a few things today to automatically detect and resolve the issue locally with out network.
