### ISSUE TITLE
How to change base64 encoded images when building wallet  ?

### ISSUE THREAD

**Issue by so121183gak** [greymass/anchor#1170]
For some reason, I can't do this and my image does not appear in the wallet, only broken icons. In developer mode, you can see that the image is attached as an empty file without a base 4 marker, why is this? 
https://drive.google.com/file/d/1R556wghDfjy7_pZZ8bRH4vNXOCzq6CaR/view?usp=sharing

**Comment by aaroncox** [comment]
Seems like it has something to do with how its being packed during the build process. That image is an SVG:

https://github.com/greymass/anchor/blob/master/app/renderer/assets/images/anchor-logo-blue.svg

And is loaded into that sidebar here:

https://github.com/greymass/anchor/blob/master/app/modules/main/containers/Sidebar.js#L11

I'm not sure why it wouldn't be appearing properly.

**Comment by so121183gak** [comment]
I understood what the matter is, it is necessary to squeeze the SVG images so that the Base64 code would be short, otherwise the postcss-svgo handler, due to the too long name, cannot add the SVG interpretation in the svg + xml; base64 format. It is necessary to compress all SVG images within 10 kilobytes

**Comment by so121183gak** [comment]
I understood what the matter is, it is necessary to squeeze the SVG images so that the Base64 code would be short, otherwise the postcss-svgo handler, due to the too long name, cannot add the SVG interpretation in the svg + xml; base64 format. It is necessary to compress all SVG images within 10 kilobytes
