### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by 4Ykw** [greymass/anchor#1171]
I can't replicate but already for several times re-occurred. Usually, after a while of being opened and working, it then happens.

Version: 1.2.6
Windows: 10.0.19042

![image](https://user-images.githubusercontent.com/6281545/132092041-bababf0e-a789-43b8-a669-8bed4ca0f485.png)

If I find more info about it, I willl update this.

**Comment by aaroncox** [comment]
I think we've isolated the problem and have a fix for it in the next release. 

We are tracking progress here if you discover anything else: https://github.com/greymass/anchor/issues/1139

Going to close this one out as a duplicate 👍
