### ISSUE TITLE
Feature request:  Add receive to wallet option

### ISSUE THREAD

**Issue by techman05** [greymass/anchor#1207]
It may just be a weird issue with my exchange but it was looking for a memo field to an account that didn't have one so I connected the account to anchor to see if I had any different options than my wallet app but I only have the option to send from the linked account in anchor and I don't see a send option. Can that be added so it can be more like a wallet.

I was hoping maybe that the wombat wallet app I use for my game was trying to limit my eos use and that going into a desktop wallet like anchor would surprise me and I'd see the memo field I don't see in that wallets app and I could send to my wallet without having to email the exchange and the wombat wallet support and anchor to find what's fudging up what is usually seems to be an easier task on other apps and wallets.

Thanks

**Comment by aaroncox** [comment]
> It may just be a weird issue with my exchange but it was looking for a memo field to an account

Yeah - some exchanges are weird and require a memo. When withdrawing from an exchange to an account, you don't need a memo for anything specifically, and can use anything you want if it requires you to enter one. 

> I only have the option to send from the linked account in anchor and I don't see a send option. Can that be added so it can be more like a wallet.

Are you talking about mobile here or desktop? The desktop version has an option to send/transfer tokens, but that doesn't exist in mobile right now. You can use Anchor to log into our web wallet and perform actions though. Most user interfaces we design will live in the web wallet now.

https://unicove.com

I'm also going to close this out. If you have bugs to report, feel free to post them here on Github, but for discussion's I'd just ask that we move things to the forums:

https://forums.eoscommunity.org/c/greymass/anchor-wallet/5
