### ISSUE TITLE
Wrong link of bloks.io for other blockchains

### ISSUE THREAD

**Issue by KevinTuncer** [greymass/anchor#1208]
For checking the transaction ID a link to bloks.io is provided, even if the test network kylin is used. But in that case the link should lead to kylin.bloks.io/transaction/{trxID}

**Comment by aaroncox** [comment]
I believe we have a fix for this in our next release (1.3.2), which will hopefully be out soon 👍

**Comment by aaroncox** [comment]
Closing old issue - please re-open if the issue persisted through the various updates we've done!
