### ISSUE TITLE
I am having issues while playing the FW game as the account type is changed from Active to Owner 

### ISSUE THREAD

**Issue by sohailshaikh333** [greymass/anchor#1223]
Hi Team,
Can you please help me resolve the issue? I had a wax wallet account sohail.gm which was an Active type of user, today morning somehow my app data was not there so I thought of restoring the account using the certificate and mnemonics which end up in creating an Owner type account. Can you guys please help me resolve the issue? How can I restore the active type user and how to get the game started again.

Thanks,
Sohail

**Comment by aaroncox** [comment]
Apologies for the late response on this - we don't actively monitor github for user support.

If you need assistance still, feel free to reach out to support@greymass.com!
