### ISSUE TITLE
can't display tools on the left panel.

### ISSUE THREAD

**Issue by ablozhou** [greymass/anchor#1226]
# env
- windows 10
- anchor 1.3.1/1.3.2 

# error
can't display tools on the left panel. 

and only display a anchor logo on the top and version info at the bottle.

# dev 
there are many warnings like below:

```
DevTools failed to load SourceMap: Could not parse content for file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/renderer/main/listenDevices.js.map: Unexpected end of JSON input
index.html#/home/accounts:1 Failed to decode downloaded font: file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/9c395283407ec055ed3e5feed77ff605.woff2
```

**Comment by aaroncox** [comment]
The Tools section isn't displayed until you setup your first account.

You can however make it display by going into Settings (gear in the top right) and enabling "Advanced User Options".
