### ISSUE TITLE
Anchor Wallet unable to connect to Ledger Nano X

### ISSUE THREAD

**Issue by sweebeng007** [greymass/anchor#1227]
Hi Guys,

I'm trying to connect my Ledger Nano X to the Anchor Wallet but to no avail.
My Ledger is already connected & unlocked but the connecting status just goes on forever.
Please see screenshot below for detail.
Appreciate your kind assistance.
Many thanks.

![image](https://user-images.githubusercontent.com/59407435/147378421-64011d30-7ec8-47ac-b07a-e3956fbf1851.png)

Best Regards
Mike Ho

**Comment by aaroncox** [comment]
Few things to try:

- Clicking Disable and then Enable again for the Ledger service sometimes kicks it and connects it immediately.
- Close other applications that may be monopolizing the connection to the Ledger device, then try again.
- If all other potential applications are closed that could be using it, and it still doesn't work, it's possible its stuck in a reconnecting state with one of them. A reboot of the computer will often resolve the problem so long as you open up Anchor first.
