### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by agent010** [greymass/anchor#1228]
Can not connect to either EOS account (linuxox.gm)

**Comment by aaroncox** [comment]
The account looks to exist (https://bloks.io/account/linuxox.gm), but its possible the API you're using isn't compatible with account lookups or the key isn't correct.

We did a few days ago find a lookup bug in our APIs and resolved that, so it may be working now if you're using our APIs. 

If you're not using our APIs and have changed it, I might recommend changing them back (https://eos.greymass.com) which you can do from the "Manage Blockchains" section of the app.
