### ISSUE TITLE
New TLOS Wallet Type + new kind of Private Key

### ISSUE THREAD

**Issue by CryptoSzr52** [greymass/anchor#1230]
Jo TLOS launched a new typ of Wallet Ending (.apx) its the Wallet for the Social Media Platform Appics. Users from iOS get Privat Keys with the beginning "PVT_R1_" and thats why the import does not work. I dont know from which side is the issue. TLOS or Anchor. 

I hope you guys can fix it. 

Thanks

**Comment by aaroncox** [comment]
What kind of device are you using Anchor on, desktop/iOS/Android?

**Comment by aaroncox** [comment]
Closing this out since it's not a bug report and more support related. If you're still having issues, please reach out to support@greymass.com.
