### ISSUE TITLE
Newly Created Wallet - I can't purchase RAM, I can't stake NET as well

### ISSUE THREAD

**Issue by zekezya** [greymass/anchor#1241]
Hello Guys,

Hope someone can help me with this. I created my 2nd wax account using Anchor Wallet. Same procedure I did before, I fund my account. Then when I was about to purchase RAM for the first time, it didn't let me. It says I don't have enough NET. So next, I did try to stake NET, but a pop-out message says that I don't have enough RAM to use. So I am running in a circle now. 

Hope someone can advise me a solution on this one.

Great thanks if ever,
Marvin

**Comment by aaroncox** [comment]
Sorry about the delay - did you get this figured out? 

The NET cost should be covered for you. A few questions that might help me figure out what's going on if you're still having problems:

- Which interface are you trying to use to buy RAM? (The interface should be providing NET)
- What's the account name that's having this problem? (We can check our logs)
