### ISSUE TITLE
Создание учетной записи Ledger с помощью якорного кошелька

### ISSUE THREAD

**Issue by TonyMontana87** [greymass/anchor#1243]
Hello! Please tell me. I wanted to create an account in a fairy tale wallet, created a public key, but the payment failed and a unique account name was not created either.

How to create a Ladder account with an anchor wallet?

**Comment by TonyMontana87** [comment]
The fact is that when sending eos to a ladger from an anchor wallet, you must enter the name of an account that does not exist. There is only a public key

**Comment by aaroncox** [comment]
We can't help you with Fairy Wallet, it's not a product we're familiar with. 

You are free to use our account creation service (https://create.anchor.link) to create a new account through Anchor. The purchase is done through the website, which then launches Anchor to finish the creation process. 

If you are using the desktop version of Anchor, it'll offer an option to use your ledger to create that account.
