### ISSUE TITLE
Desktop - Fix Telos block explorer links (bloks.io no longer works)

### ISSUE THREAD

**Issue by aaroncox** [greymass/anchor#1246]

**Comment by Setland34** [comment]
i need access to my wallets, can you please help me get setup ?

**Comment by tonytuba** [comment]
We'll get a look at this shortly, but for the time being, here's the link to the Telos block explorer.

https://explorer.telos.net/network

**Comment by masoudahg00** [comment]
> @masoudahg00 @masoudleyli FIO6UQ9NdUbLvXg5uyKYqPDtZo1s8nsPTLPsL2US3WAkUzgkYu4KE 
Amount: 88000FIO
- [x] `@masoudahg00``` @masoudleyli @masoudahg1 #6279 #6514 #1 #2 #3 #4 #5 #6 #7 #8 #9 #10 #11 #12 #13 #15 #14
