### ISSUE TITLE
Exception appears if you press View - Refresh multiple times

### ISSUE THREAD

**Issue by petervalencic** [greymass/anchor#1259]
The issue happens if you press or select the View -> Reload while the app is still loading the main form..

To reproduce the issue you need to:
1.) select the View option in the main menu
2.) select the Reload option
3,) repeat the operation many times

The issue will not happen if you press ctrl+R multiple times..

![image](https://user-images.githubusercontent.com/10866388/160564087-c8a91939-750e-4aef-930e-034dc0ced41c.png)

![image](https://user-images.githubusercontent.com/10866388/160564139-b3b06b17-f179-41fd-8c75-259cf031f0e5.png)

**Comment by aaroncox** [comment]
I for whatever reason cannot reproduce this. It successfully reloads each time. 

Considering that I don't think people are actively going to do this - I'm not going to spend too much time hunting this one down 😅
