### ISSUE TITLE
Is the keypair generator linked to a seed phrase?

### ISSUE THREAD

**Issue by littleboy0k** [greymass/anchor#1332]
### Platform

Desktop (MacOS)

### Description

My question is about the Key Generator built into the app. When I click generate key pair, is the generated key associated with the seed I imported from scatter or any other seed phrase? Or are they totally new and independent and can't be generated with any other mechanism? Sorry to bother but I couldn't find any info about my query. Hence, I am asking here.

![image](https://user-images.githubusercontent.com/32856591/215684509-90ef6ec0-57b5-4060-8470-ebeadad998cd.png)

**Comment by aaroncox** [comment]
Hey - apologies for missing this! The keys generated in that section are completely independent of one another. There's no common seed phrase in Anchor that all keys are derived from.
