### ISSUE TITLE
Missing Win x64 build for Anchor (1.3.10)

### ISSUE THREAD

**Issue by tonyping** [greymass/anchor#1346]
### Description

The latest release of [Anchor (1.3.10)](https://github.com/greymass/anchor/releases/tag/v1.3.10) seems to be missing for Windows x64. 

I see an "win-anchor-wallet-1.3.10-x64.exe.blockmap" file, so I assumed there would be a corresponding win-anchor-wallet-1.3.10-x64.exe?

### Platform

Desktop (Windows)

**Comment by aaroncox** [comment]
The upload apparently failed. It's been uploaded so v1.3.10 should work now. Since then v1.3.11 has also been published with some account creation fixes 👍

**Comment by tonyping** [comment]
> The upload apparently failed. It's been uploaded so v1.3.10 should work now. Since then v1.3.11 has also been published with some account creation fixes 👍

Awesome, thanks!
