### ISSUE TITLE
Anchor fails to sign transactions

### ISSUE THREAD

**Issue by scottoau** [greymass/anchor#779]
When signing a transaction via the EOSIO Signing Requests dApp Integration Control (bloks.io) I receive the following error message. 

<img width="931" alt="Screen Shot 2020-01-29 at 11 14 24 pm" src="https://user-images.githubusercontent.com/40372886/73360183-1b8b8700-42ee-11ea-90f5-155550cb5ad7.png">

I've tested multiple accounts, actions, and contracts, the error message remains the same. 

Refreshing vote and transferring tokens worked through the Anchor UI. 

Version 1.0.0-rc5 (1.0.0-rc5)
OS. Mac 10.15.2

**Comment by aaroncox** [comment]
I'm having a difficult time reproducing the error to debug, so a few questions:

- Does this happen immediately when prompted for the request or after clicking one of the buttons?
- What type of account is loaded, a generic wallet with a private key?
- Was this a fresh wallet setup or a restore from a backup?

Also if you wouldn't mind reproducing the issue yourself and getting more information, there should be a more detailed error message in the developer console. If you right click on the signing window and click "Inspect Element", the developer console will open. Then click on the "Console" tab and very likely some red error text should also be displayed there. 

If it is not immediately displayed - once the error console is open, trigger another signing request and it should display an error. 

I'll continue to try to reproduce this so I can debug further, but any additional information will help!

**Comment by aaroncox** [comment]
Alright - we isolated the problem and have a fix for this in our development build. No worries about the questions above, and we'll have a fix out for it soon.

**Comment by scottoau** [comment]
@aaroncox thanks for the update. Was going to do the testing today but will put it on hold.

**Comment by dafuga** [comment]
Hey @scottoau I believe that this has been fixed on our latest release (https://github.com/greymass/eos-voter/releases/tag/v1.0.0-rc7). Will leave this issue opened for now so you can you try it out and let us know if you are still experiencing the issue.

**Comment by scottoau** [comment]
Hi @dafuga it's working fine now. All fixed. Thanks for sorting it out.
