### ISSUE TITLE
WAX load from Ledger seems broken

### ISSUE THREAD

**Issue by aaroncox** [greymass/anchor#790]
This is likely due to some changes I made in the most recent build.

![image](https://user-images.githubusercontent.com/677686/74761575-43656f00-524a-11ea-844c-155c3d35ecf3.png)

**Comment by AlpineDan** [comment]
WAX Ledger import works for me :-)

- Anchor v1.0.2 (deb package on Linux Mint 19.3).
- Ledger EOS App 1.3.1.

**Comment by aaroncox** [comment]
Can confirm, we must have fixed this and forgot to close out the issue!

Thanks for bumping this one
