### ISSUE TITLE
API Recommender hangs

### ISSUE THREAD

**Issue by robrigo** [greymass/anchor#841]
I'm looking through the tools and noticed the API recommender seems to be hung.

<img width="1124" alt="Screen Shot 2020-04-10 at 2 35 06 PM" src="https://user-images.githubusercontent.com/590263/79014328-a97abe00-7b38-11ea-8a40-ac39eeb6bfef.png">

**Comment by aaroncox** [comment]
Just added a message for incompatible chains if you try to launch it. 

In this specific instance, the `producerjson` contract needs to exist so it has a set of APIs to test against. Right now I believe it's just spinning because it has an empty list of APIs to test against!
