### ISSUE TITLE
help, i m still on eos voter 0.2.1

### ISSUE THREAD

**Issue by ikkaku999** [greymass/anchor#865]
Hi and thx for reading.

I m still on eos voter 0.2.1, so no backup option;

I can t find eos voter 0.4.1 or higher, so i cant do a backup to migrate to anchor.

I did Dl Anchor, and it seems good.

Is there an easy way to do the migration of my waller?

Thx

**Comment by aaroncox** [comment]
Another method you could use to accomplish this is just setting up a new wallet in Anchor and import the private keys. I assume you have the private key backed up somewhere still? It's always recommended, in the event that for some reason the wallet crashes and loses that data. 

0.2.1 is super old, so if you choose to upgrade that, I'd def recommend you have a backup of your private keys handy in the event that the upgrade doesn't work. We did have some problems with upgrades early on with users reporting that their wallets didn't convert properly.

If you do want to upgrade eos-voter to the latest version, and have that backup, it can be found here:

https://github.com/greymass/anchor/releases/tag/v0.7.12

Once you have 0.7.12 installed, the backup option should exist, which you could then use to migrate over automatically to Anchor.

**Comment by ikkaku999** [comment]
thanks a lot  , it worked fine with private keys!!!! Anchor is super smooth!
