### ISSUE TITLE
WAX: Unable to stake CPU/NET beyond 4 decimal places

### ISSUE THREAD

**Issue by AlpineDan** [greymass/anchor#891]
WAX tokens have a decimal precision of 8 decimal places. In v1.0.2 it's not possible to click "Stake" for values with more than 4 decimal places in the pop-up when adding to CPU/NET in the "Resources" tab.

- Anchor v1.0.2 (deb package Linux Mint 19.3).

![AnchorStakeWax](https://user-images.githubusercontent.com/65924701/82844535-1f689800-9ee1-11ea-91df-ef8bd1c28812.png)

**Comment by aaroncox** [comment]
Thanks for the heads up on that - it looks like we missed a spot where we validate the value.

**Comment by aaroncox** [comment]
The above commit fixes this and will be made available in the 1.0.4 release 👍
