### ISSUE TITLE
FIO watch account import doesn't allow @

### ISSUE THREAD

**Issue by maxocoin** [greymass/anchor#898]
FIO accounts have an @ in their names.
When you try to import a Watch account, when you type the @ the "Find" button gets disabled 
Typing a public address is not allowed either 

![image](https://user-images.githubusercontent.com/30597258/83081330-558c5000-a078-11ea-87ae-94e040e3a820.png)

**Comment by aaroncox** [comment]
What you'd use here is the actual FIO account name, as opposed to the address or public key. 

It's sort of confusing still - but we haven't integrated the FIO protocols themselves yet. 

As an example, our block producer account on testnet has these 3 identities:

FIO Address: `teamgreymass@fiotestnet`
FIO Account Name: `54givmsg2zii`
FIO Public Key: `FIO8RcFfrxmfLFYddJyYFpWUZApQn34Pn1Zk7HfdryEQdW577iLVw`

The screenshot you listed above would want the account name, which is the `54givmsg2zii` value. 

![image](https://user-images.githubusercontent.com/677686/83083162-6bd3e500-a053-11ea-9936-5fe9b736f5b1.png)

Once we have a deeper integration with the FIO protocol itself, we'll be able to do lookups by FIO Addresses, but until then all the account features will still need to use the FIO Account Names.
