### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by ZacheryGlass** [greymass/anchor#914]
- Windows 10
- Anchor Wallet 1.0.4

I just installed the app, and clicked "Setup Cold Wallet". Then I click View -> Reload, I get the following error:

![image](https://user-images.githubusercontent.com/21087424/84049078-9b4af180-a971-11ea-8b13-b2a12e8a047b.png)

Also, the "Cancel" button on when creating a cold wallet does not work. The only way I was able to exit this page is to completely reset the wallet by clicking the bottom left corner, and clicking "Reset Application"

**Comment by aaroncox** [comment]
We should have a fix for this error in the next build, it looks like the node validation was trying to connect despite being setup as a cold wallet.

**Comment by aaroncox** [comment]
Both are available in 1.0.5 - thanks for reporting these!
