### ISSUE TITLE
Is the Anchor IOS version open source? I did not see the corresponding code on github

### ISSUE THREAD

**Issue by cppfuns** [greymass/anchor#918]

**Comment by aaroncox** [comment]
Currently it is not. We plan on open sourcing the iOS version after it's released.

We have published a number of swift libraries we used in it's creation though:

https://github.com/greymass/swift-eosio
https://github.com/greymass/EllipticCurveKit
https://github.com/greymass/swift-scrypt
https://github.com/greymass/swift-eosio-key-encryption
https://github.com/greymass/swift-base2048
