### ISSUE TITLE
TX incorrectly uses ABI from another chain

### ISSUE THREAD

**Issue by aaroncox** [greymass/anchor#921]
A situation was reported with the error message of: 

`Unknown action deposit on contract eosio`

The users was trying to use bloks.io to deposit into REX on EOS, and previously had been using WAX. 

I think there's a situation here where signing requests are using the ABIs from the wrong chain to try and create signatures for signing requests. We need to go through the processes and ensure the right ABI is called, and potentially if failed, reload the ABI.

**Comment by maxocoin** [comment]
I had a similar issue
I was using EOS and then logged in at wax.bloks.io with my WAX account.

When I try to claim my rewards I got the message 

![image](https://user-images.githubusercontent.com/30597258/91658036-de72b780-eabd-11ea-9f45-e133e8b5e75d.png)

After restarting Anchor and reloading wax.bloks.io a few times I finally managed to sign the transaction.

It happened a few times already, what information  should I look at the next time?

**Comment by aaroncox** [comment]
Thanks for the heads up on this and I think the information you provided is good enough. We have an ABI cache in Anchor and I'm wondering if maybe the original issue I reported from another user is the root of the same problem, and maybe that cache is being used across chains (which it shouldn't). It could explain why the REX actions weren't on the EOSIO ABI, if they were using a chain before hand that doesn't have those actions.

Going to bump this one up and put it on our current milestone, and I'll see if we can get a fix out in the next beta.

**Comment by aaroncox** [comment]
The fix for this should be included in 1.1.0 👍
