### ISSUE TITLE
Exchange Account Auto Completion ?!?

### ISSUE THREAD

**Issue by kaefergeneral** [greymass/anchor#942]
I just had a huge WTF moment realizing that Anchor is providing deposit adresses for exchange accounts.

But for some stupid reason it is not distinguishing by chain, so you are luring noobs to depositing funds to scammers and squatters.

**Comment by aaroncox** [comment]
You're right, and those 100% should be chain-specific and that feature shouldn't be bleeding into other chains.

We'll make sure that change gets into the next release.

**Comment by aaroncox** [comment]
1.1.0-beta-1 has the fix for this and will be included in the final 1.1.0 release.
