### ISSUE TITLE
Is this a Bug? Greymass and anchor give me symbol mismatch for my Telos and EOS KANDA (contract: telokandaone ) 

### ISSUE THREAD

**Issue by ackza** [greymass/anchor#944]
When I tried to send telos or EOS kanda from Greymass or now Anchor, I would get symbol mismatch errors. telokandaone on telos and eos, has 8 decimal precision, is  that an issue? I hope I can manually set my default precision so I don't have to manually type in exactly the number of 0s everytime

![image](https://user-images.githubusercontent.com/33010254/89134099-0b3fa900-d4d7-11ea-842a-4ee16a637946.png)

**Comment by aaroncox** [comment]
Looks like this is a bug, we'll see if we can get it fixed for the next release. It's defaulting to 4 for some reason when it should be 8.

**Comment by aaroncox** [comment]
This will be resolved in 1.1.0 upon release.
