### ISSUE TITLE
Telos Blockchain link on Anchor is wrong

### ISSUE THREAD

**Issue by nt300** [greymass/anchor#946]
Good Evening, 
The Telos Blockchain Link on Anchor Version 1.0.5 is incorrect. ****
The link reads as https://api.eos.miami:17441

The proper link I believe is the following
Host api.telosfoundation.io
Protocol https
Port 443

So I cannot access my Telos wallet on Anchor because it simply won't connect. When I tried to connect to it online the **web-page** said cannot be accessed. 

Thank You,

**Comment by aaroncox** [comment]
That looks to either be an old default or one that came over from a backup. 

You can manage these yourself and use whichever API you'd like by clicking the "Manage Blockchains" option and then editing the Telos chain. From there, you can set the API endpoint to that of your choosing. 

We also offer a Telos API, which you're free to set it to. Ours is https://telos.greymass.com, which is actually the default right now.

**Comment by nt300** [comment]
Hello,
It worked.
Thank you very much.
Wasn't sure if I had to reply back or not.

Cheers,
Nick

Sent via BlackBerry Hub+ Inbox for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
