### ISSUE TITLE
Error message while trying to transact with disconnected Ledger Nano S

### ISSUE THREAD

**Issue by jtf420** [greymass/anchor#950]
While trying to sign a transaction on EOS chain with a disconnected Ledger it gives a error message;
_Error e.decorateAppAPIMethods is not a function_

simple user understandable error message that device is disconnected will be great. The USB device connection Icon doesn't attract attention by pop-up/Blink-info on hover when the above mentioned error occurs.

**Comment by aaroncox** [comment]
We added some better error handling recently which should be catching this.

Which version did you experience this on? 

Also, do you have any steps that you can perform to reproduce this?

**Comment by aaroncox** [comment]
For reference, these are the two errors we added, one for when the service is completely disabled and one for when the it's enable but Anchor is unable to communicate with it.

![ledgererrors](https://user-images.githubusercontent.com/677686/89932105-1d0e0400-dbdb-11ea-9b7e-78255aa94af4.gif)
