### ISSUE TITLE
Scatter adapter: Allow connecting with Anchor when clicking Scatter login

### ISSUE THREAD

**Issue by Soleone** [greymass/anchor#951]
# Problem

Many dapps do not have a login option for Anchor yet. A lot of them still only support connecting via Scatter.

# Suggestion

Could it be possible to write some sort of Scatter API compatibility layer where websites don't have to be upgraded to work with Anchor?

What are counter-arguments against such an attempt?

- Is the API between Scatter and Anchor too different? If so what is Scatter missing?
- Is it an unreasonable amount of work to build such an adapter?
- Is is reasonable enough to not support old dapps or push the developers to implement the Anchor API?

**Comment by jnordberg** [comment]
We have discussed this internally and while possible to implement as a chrome extension or a standalone app that runs a websocket server acting as a bridge it would be a lot of work that we can't justify. We feel it's better to spend our limited resources on improving and helping dApps implement wallet abstraction layers (e.g. ual or transit) so this won't be a problem in the future.

**Comment by aaroncox** [comment]
We think it'd be possible to build a bridge like that, but it'd likely wouldn't be 100% compatible and it would require each user to install the bridge to work. It'd have to be an extension or standalone app of some kind. That's a large ask from the user/UX perspective, especially compared with the alternative of just having the dapp/website change their approach.

The fundamental ways these two signing protocols work is just different enough that it makes it difficult to come up with a better solution. Scatter-based integrations (scatter-js) expect a local webserver running on the client (Scatter, etc), where as Anchor was designed to never act as a server, so it would never be able to respond to those requests.

If anyone would know how to do it better though, I assume it'd be the Scatter team. You guys may know of a more clever way to convert a Scatter-style request into an ESR request within the scatter-js plugin ecosystem. But as I started off the message with, there are likely additional incompatibilities between the two protocols capabilities that might cause some headaches.  

Ultimately I think dapps just need to start using a wallet abstraction layer like UAL or Transit. That way they can just turn on/off wallet providers as they see fit without needing to fiddle with their code too much.

**Comment by Soleone** [comment]
cc @nsjames just for your info on the Scatter side.

**Comment by nsjames** [comment]
Though converting the transaction into ESR would be easy on the ScatterJS side, the non-existence of a pre-known wallet makes it problematic since ScatterJS doesn't make users select the wallet they want to use, but instead infers it from available endpoints. 

It would require changes to the general philosophy of the library; which is "no user intervention required apart from login"
