### ISSUE TITLE
Error Expected string containing name during tranfser on binance

### ISSUE THREAD

**Issue by Gabbiano83BG** [greymass/anchor#953]
I'm trying to transfer to Binance exchange some EOS token, but after specify MEMO and quantity I got this error (see screen)

![immagine](https://user-images.githubusercontent.com/69907580/90641844-f7fc3f80-e231-11ea-99f7-aec8c38d4422.png)

Anyone could help me?

Previously I've migrated my wallet from eos-voter to Anchor.

**Comment by aaroncox** [comment]
I am trying to figure out the cause of this, so one question I have is can you transfer to other accounts successfully? I'd be interested to know if you were able to send 0.0001 as a test to any other account. 

If you can't transfer anywhere, then I think it may be the wallet, and the best course of action would be to reimport the keys. I suspect something may have gotten messed up in the migration from eos-voter to Anchor, but am not sure.

**Comment by Gabbiano83BG** [comment]
Solved changing the wallet, This Issue can be closed.

Thanks
