### ISSUE TITLE
Windows, Anchor close, opening a signing request will open Anchor but not trigger the request.

### ISSUE THREAD

**Issue by aaroncox** [greymass/anchor#958]

**Comment by maxocoin** [comment]
I have the same problem with Anchor Open
I used Anchor for login but after trying to sign a tx it times out 

![image](https://user-images.githubusercontent.com/30597258/93081123-aacf8a00-f686-11ea-809a-ba5d0b3b1475.png)

**Comment by maxocoin** [comment]
I managed to repeat it with the debug window open, I don't see any relevant errors 
![image](https://user-images.githubusercontent.com/30597258/95049435-a7f21300-06e1-11eb-8c11-d4247527ffe2.png)

**Comment by xgfreon** [comment]
Having a similar issue. Says open anchor desktop view and sign transaction. I dont see any transactions to sign on the desktop. If i open the mobile app though it pops up automatically.

**Comment by aaroncox** [comment]
@xgfreon If I'm understanding you correctly - unfortunately right now, you can only be logged in to a single website (like bloks etc) with either desktop or mobile. If you were logged in with desktop and then logged in with mobile afterwards, the mobile session would replace the desktop session. 

Also closing out this issue since I believe we resolved the issue specific to the original bug report last August 😅
