### ISSUE TITLE
Could we add a switch for avoid the QR screen?

### ISSUE THREAD

**Issue by maxocoin** [greymass/anchor#969]
Hi,
When you are fully on desktop, stopping every single time on the QR screen can get a bit tiresome 

Could it be possible to add a switch on the QR screen that says something along "Next time, go directly to the singing screen"

Switching back the QR screen could be enabled on Wallet options (when you turn it off, a hint about it, would be nice) or on the actual signing screen (show QR the next time)

**Comment by aaroncox** [comment]
Are you referring to a specific app? 

With 1.1.0 released - it's up to the applications themselves now to implement sessions, which removes all of the QR codes except the first one that is displayed as you're signing in for the first time.
