### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by lexansoft** [greymass/anchor#970]
Installed the latest 1.1.0 on ubuntu. Now I get this error every time:

Cannot read property 'startsWith' of undefined
![Screenshot from 2020-09-07 15-19-12](https://user-images.githubusercontent.com/2127780/92418721-cc2bf580-f11d-11ea-93e1-8ba00e1b3853.png)

**Comment by aaroncox** [comment]
We're looking into this and hope to have a fix out soon in 1.1.1.

**Comment by aaroncox** [comment]
https://github.com/greymass/anchor/releases/tag/v1.1.1

I believe we have the issue resolved. Give it a shot and if you're still experiencing the same issue, feel free to reopen this issue. If it persists we may need a bit more information (like the link inside the signing request if you were to click the "Share Request" button inside the screenshot shared)
