### ISSUE TITLE
EOS-Voter wallet same name as BTS account, how to transfer between?

### ISSUE THREAD

**Issue by Cryptostar33** [greymass/anchor#971]
EOS-Voter wallet has same name as bts.beos.world wallet and therefore when wanting to send bts or BEOS to EOS-voter, the SEND button doesn't light up... How to get BEOS onto EOS-voter wallet with same name? Without buying new BEOS account?

**Comment by aaroncox** [comment]
They have their own fork of the wallet which they maintain, I'm not sure what's changed within that one. 

If you are just looking to move between their version of eos-voter and our version (now called Anchor), you shouldn't have to send any tokens - you'll just need to import the keys into Anchor. You'll then have access to your tokens.

However, if you're talking about transferring tokens between chains - it doesn't use the normal Wallet Transfer page, it uses a special "Crosschain Transfer" interface which you can find under the Tools section. Using that interface will allow you to use the gateway the BEOS folks have setup and transfer from BEOS to BTS.
