### ISSUE TITLE
UX Network Account Zero-Available Quandry: Cannot buy RAM, Cannot Unstake NET/CPU

### ISSUE THREAD

**Issue by TrentScott** [greymass/anchor#975]
Using Anchor 1.1.1, cannot buy RAM or unstake resources, account is basically unusable:

0 UTX available (100% staked)
1+ million staked CPU
1+ million staked NET
11K+ UTXRAM

When attempting to purchase 1024 bytes of RAM:
"Insufficient available balance to complete transaction."

When attempting to unstake just a few thousand NET:
"account genesis111cm has insufficient ram; needs 4105 bytes has 4096 bytes"

In a Catch-22: not enough ram to unstake cpu/net, and not enough UTXRAM (although I have 11K+ in the account) to purchase a small amount of RAM.

**Comment by aaroncox** [comment]
Does the RAM purchasing screen show a balance? It's interesting that the UI is blocking the purchase despite you having the available UTXRAM balance.

One potential thing that may have happened is the configuration got screwed up somehow - which may be able to be resolved if you reset the application (via Tools), which will restore all the defaults, and then reimport your keys into a fresh wallet. Just be sure before you reset that you have a backup of all of your private keys to avoid erasing that data!

**Comment by TrentScott** [comment]
Not sure what screen that is, so attached 3 images and hopefully one of them is what you're referring to.

I have the keys safely archived elsewhere, so I will attempt the reset and re-import...

**Comment by aaroncox** [comment]
On the 3rd screenshot, this part leads me to believe the configuration may have gotten corrupted somewhere between 1.0.5 and 1.1.1.

![image](https://user-images.githubusercontent.com/677686/92810183-52993f00-f38b-11ea-808f-d42f3b3a8c9b.png)

That section should display `UTXRAM Balance` and then display how many tokens you have. I'd give the reset a try, and see if that fixes it. We'll dig on our end to see if we find anything wrong with that section as well.

**Comment by TrentScott** [comment]
The reset/reimport worked just fine.  Just purchased and doubled available RAM.  Thanks for your support!  
![image](https://user-images.githubusercontent.com/11326159/92818519-08ad5a80-f385-11ea-95ea-c2351a834f65.png)

**Comment by aaroncox** [comment]
Awesome, glad that worked! Hopefully this bug will only happen to the select few who went through and used 1.1.0 - and those who start using 1.1.1 and beyond won't experience this. Thanks for letting us know!
