### ISSUE TITLE
Error when logging into newdex or bloks (LinuxMint) after upgrading to 1.1.2

### ISSUE THREAD

**Issue by interwebcoding** [greymass/anchor#982]
![image](https://user-images.githubusercontent.com/4772380/93056931-b4192080-f69f-11ea-9a93-f20331c7c545.png)

only experience the error when logging in.  Once logged in, i can place an order and execute with no similar error.

As per subject line - tested and got the same error on Newdex and bloks.

**Comment by aaroncox** [comment]
https://github.com/greymass/anchor/releases/tag/v1.1.3

This should now be resolved as of 1.1.3, please re-open if the problem persists. Thanks for the report!
