### ISSUE TITLE
General macOS issues on 1.1.x

### ISSUE THREAD

**Issue by robrigo** [greymass/anchor#989]
Hello! I just wanted to drop in and report some issues I am experiencing with the latest Anchor (1.1.4) on macOS 10.15.6. First of all, the app seems a lot more laggy than it used to be.

Next, I can't sign anything now when I try to log in on a site, instead I get the following popup error.
![Screen Shot 2020-09-16 at 11 13 53 AM](https://user-images.githubusercontent.com/590263/93357645-8c949600-f80e-11ea-93b9-120624f7a612.png)

This issue was created signing into app.vigor.ai with an EOS account.

Also, a lot of times when I return to a site, I have to completely close Anchor and re-open it or else it just hangs on a signing popup in the web app and doesn't actually open the Anchor prompt to sign.

**Comment by aaroncox** [comment]
Should all be resolved in 1.1.5 😉 

https://github.com/greymass/anchor/releases/tag/v1.1.5
