### ISSUE TITLE
Wallet opens to blank screen with app title "Signing Request"

### ISSUE THREAD

**Issue by tomosaigon** [greymass/anchor#992]
App is in an unusable state because every time I open it, the whole app is white/blank. The title is set to "Signing Request - Anchor Wallet".

**Comment by aaroncox** [comment]
Which version? I believe we have this resolved as of 1.1.5, but would like to confirm

**Comment by tomosaigon** [comment]
I'm running 1.1.5. Some combination of keys/escapes was able to get out of it.

**Comment by aaroncox** [comment]
Escape will close it, if it has focus (click on it if it doesn't). 

We'll dig back into this and see if we can see why it might still be triggering.
