### ISSUE TITLE
Ability to force Fuel ?

### ISSUE THREAD

**Issue by maxocoin** [greymass/anchor#993]
From time to time, when the available CPU is low, the DAPP shows the "Detecting if Fuel is necessary" and detects that it is not.

But after signing the TX (without the Fuel noop) you get the "not enough CPU" error, like this one, depositing on Vigor
![image](https://user-images.githubusercontent.com/30597258/93882278-e6e29a80-fcd7-11ea-8f66-a12af7c2a06a.png)

The problem is that repeating the TX doesn't detect that the CPU is not enough 

Could it be possible to have a "pay with FUEL" in the signing screen for cover those corner cases?  Or does that need to be done on the DAPP end?

**Comment by aaroncox** [comment]
I think we could potentially do that on our side. It's be a weird UX though, since we'd have to then make them trigger and sign the transaction again after the first failure - but that's probably better than just having it fail over and over.

**Comment by maxocoin** [comment]
Is the result of "checking if Fuel is necessary" resolved  by you or the DAPP?  
Because if it is resolved my Anchor, you could always return "true" when a second identical request  arrives 

e.g. the first TX is signed normally but it will fail, the second time a "checking for fuel" call arrives with the same parameters (or if there is a way to check if the previous tx failed) you always return that Fuel is needed

**Comment by aaroncox** [comment]
It's resolved using our APIs within the DAPP itself. 

Things get a bit crazy if we modify transactions sent by the DAPP, so we've decided to implement all of that logic in the browser and in the DAPP, and then Anchor just respects what's sent along.

**Comment by aaroncox** [comment]
We're working on this externally of Anchor - in the @greymass/anchor-link repository and a new project. I'm going to close this out since we're tracking development of features to improve this elsewhere and am cleaning up issues here.
