### ISSUE TITLE
FEATURE REQUEST Build In Alcor DEX custom JSON templates to make manual dex trades, pool swaps and listings easier to do from anchor when websites are down

### ISSUE THREAD

**Issue by ackza** [greymass/anchor#994]
to prove alcor works even when website is down, we should make it so anyone can send any any amount of any eos token to accounts from anchor 

If we get anchor integrated we should also be allowed to use an wallet, if we memorize the memo formatting necessary to make simple buy and sell orders on the eosio dex alcor.exchange but if a system lets us plugin modular templates for various "skills" one day do with memo txs, we could see listing, buying selling and one tx swaps as options for formatting a transaction. Theres also Telos transaction formatting we need to help proposals get done direct from anchor, without needingbloks.io and thats an example of how powerful we can make anchor on its own. 

Add alcor.exchange dex trading options for each tx with a simple memo auto filler, giving you automated fields that allow a tx to initiate a trade of a token a whatever the recent price is, feeds and order books can show up or not, they can just be hidden and users just are shown the most recent bid or ask and volume of the day

thus we wont even need the website, and we shouldnt have to depend on one website, hardcore users should be usin anchor and wombat and bloks.io anyway.

**Comment by aaroncox** [comment]
As with the idea for NFTs, this is likely something we won't add directly into Anchor, but into some external sort of product. 

Anchor at this point is moving the direction of being an "Authenticator" first, with most app-like functionality existing outside of it. This is the type of app-like functionality that I'd expect to integrate with Anchor in some form of external application.
