### ISSUE TITLE
Transaction's reference block did not match. Is this transaction from a different fork?

### ISSUE THREAD

**Issue by maxocoin** [greymass/anchor#997]
I have been getting this error trying to send funds using bloks on the EOS main net. 

I log-out and login two or three times and  the TX gets through

**Comment by aaroncox** [comment]
We have been looking into this, and seeing reports in some of the developer channels as well on the same issue. I'm beginning to think it's a network related issue, but we're investigating.

**Comment by aaroncox** [comment]
Was this a ledger account?

**Comment by maxocoin** [comment]
No, it was not a ledger account, I pasted the private key into Anchor

**Comment by aaroncox** [comment]
I believe we have this issue resolved as of 1.1.8.
